### ISSUE TITLE
(iOS) Issue creating build relating to proverDeleteCredentials due to old IndyFramework

### ISSUE THREAD

**Issue by JamesKEbert** [hyperledger/indy-sdk-react-native#38]
Hi folks! We've recently encountered an issue with releases 0.1.17 and newer with proverDeleteCredentials when building for iOS:
<img width="1265" alt="Screen Shot 2022-04-12 at 6 12 43 PM" src="https://user-images.githubusercontent.com/30242284/163074576-dcffd3d5-a49c-411c-b034-4aed19acd07a.png">

It is unable to find the definition of proverDeleteCredentialsWithId in the Indy SDK ios wrapper--which it is there. My current hunch is that the `IndyFramework` file placed in the `Pods/Frameworks` directory is out of date/does not include this addition. 

So, my issue is two part:
1. Is this actually the issue or is it a red-herring and therefore any insight into the real problem here?
2. In the [iOS installation section](https://github.com/hyperledger/indy-sdk-react-native#ios), step 4., it references the `IndyFramework`, but does not include a reference as to where to get it (including the latest build of it). Is there a place in which this is being updated/placed, as the Sovrin iOS wrapper builds don't include anything above v1.8.2, which is not sufficient obviously. 

Thanks!

**Comment by berendsliedrecht** [comment]
Yes `proverDeleteCredential` was added in `IndyAnoncreds` relatively recently. Bifold should have the latest indryFramework complete with this function. 

I can't wait for this to be over... Its insane that we have to share xcframeworks like this.

**Comment by JamesKEbert** [comment]
Awesome--and agreed. Is this sharing problem going to be an issue with the shared libraries as well?

You think it's appropriate/okay to link to Bifold's IndyFramework from this repo?

**Comment by TimoGlastra** [comment]
Berend is doing an excellent job to improve this for the new libraries :)

You can see how it will work in the [react-native-bbs-signatures](https://github.com/animo/react-native-bbs-signatures#installation) library. It fully works with autolinking
