### ISSUE TITLE
App crashes on proverDeleteCredentials on Android 10 (Android)

### ISSUE THREAD

**Issue by nbAmit** [hyperledger/indy-sdk-react-native#43]
Hi all, I have encountered an issue while deleting the credential from wallet in android 10 device, I check that issue into the Indy SDK and found reported issue for android 10 [#2320](https://github.com/hyperledger/indy-sdk/issues/2320) 

I think to fix this we have to update indy version the `build.gradle` and readme as well
https://github.com/hyperledger/indy-sdk-react-native/blob/8b9c352e15cdcdbfa99388183d7b8a0451fc3e39/android/build.gradle#L95

**Comment by TimoGlastra** [comment]
Thanks for opening this issue @nbAmit. It seems iOS has already been updated to 1.16, but android hasn't.

Are you willing to open a PR for this? We would probably need to update the Java wrapper version but also make sure to require at least 1.16 for the binaries (currently lists 1.15 in the readme I think).

**Comment by nbAmit** [comment]
Thanks @TimoGlastra for quick update. Sure, I will work on this and raise the PR
