### ISSUE TITLE
Rename Android package

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/indy-sdk-react-native#57]
Currently, we use default `com.reactlibrary` which may cause issues if there is another library using the same thing.

Any suggestions for the name? The first that came to my mind is `org.hyperledger.indysdk.reactnative`.

**Comment by TimoGlastra** [comment]
Sounds good. What does the Java wrapper use? org.hyperledger.indysdk?

**Comment by jakubkoci** [comment]
The indy-sdk Java wrapper is using `org.hyperledger.indy.sdk`. So, maybe `org.hyperledger.indy.sdk.reactnative`?
